
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author TuyenPVT
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNewCourse = new javax.swing.JButton();
        btnSearchCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        btnAllCourse = new javax.swing.JButton();
        btnUpdateCourse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(96, 134, 240));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 248, 253));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jLabel1.setText(" ADMIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, -1));

        btnNewCourse.setBackground(new java.awt.Color(0, 0, 255));
        btnNewCourse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnNewCourse.setForeground(new java.awt.Color(0, 0, 255));
        btnNewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addcourse.png"))); // NOI18N
        btnNewCourse.setText("   New course");
        btnNewCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNewCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewCourseMouseExited(evt);
            }
        });
        btnNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCourseActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 60));

        btnSearchCourse.setBackground(new java.awt.Color(0, 0, 255));
        btnSearchCourse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSearchCourse.setForeground(new java.awt.Color(0, 0, 255));
        btnSearchCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchcourse.png"))); // NOI18N
        btnSearchCourse.setText("   Search course");
        btnSearchCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearchCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearchCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchCourseMouseExited(evt);
            }
        });
        btnSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCourseActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 280, 60));

        btnDeleteCourse.setBackground(new java.awt.Color(0, 0, 255));
        btnDeleteCourse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDeleteCourse.setForeground(new java.awt.Color(0, 0, 255));
        btnDeleteCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDeleteCourse.setText("   Delete");
        btnDeleteCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeleteCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeleteCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteCourseMouseExited(evt);
            }
        });
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 280, 60));

        btnStudent.setBackground(new java.awt.Color(0, 0, 255));
        btnStudent.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(0, 0, 255));
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students.png"))); // NOI18N
        btnStudent.setText("   Students");
        btnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudentMouseExited(evt);
            }
        });
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 280, 60));

        btnSignOut.setBackground(new java.awt.Color(0, 0, 255));
        btnSignOut.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(0, 0, 255));
        btnSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signout.png"))); // NOI18N
        btnSignOut.setText("   Sign Out");
        btnSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSignOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignOutMouseExited(evt);
            }
        });
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 280, 60));

        btnAllCourse.setBackground(new java.awt.Color(0, 0, 255));
        btnAllCourse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAllCourse.setForeground(new java.awt.Color(0, 0, 255));
        btnAllCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/allcourse.png"))); // NOI18N
        btnAllCourse.setText("   All courses");
        btnAllCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAllCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAllCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAllCourseMouseExited(evt);
            }
        });
        btnAllCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllCourseActionPerformed(evt);
            }
        });
        jPanel1.add(btnAllCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, 60));

        btnUpdateCourse.setBackground(new java.awt.Color(0, 0, 255));
        btnUpdateCourse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnUpdateCourse.setForeground(new java.awt.Color(0, 0, 255));
        btnUpdateCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnUpdateCourse.setText("   Update course");
        btnUpdateCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdateCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateCourseMouseExited(evt);
            }
        });
        btnUpdateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCourseActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 280, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 770));

        jPanel2.setBackground(new java.awt.Color(240, 248, 253));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeedit.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 530, 560));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1100, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        setVisible(true);
        new Login().setVisible(true);
        dispose();

    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnSignOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOutMouseEntered
        // TODO add your handling code here:
        setBg(btnSignOut);
    }//GEN-LAST:event_btnSignOutMouseEntered

    private void btnSignOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOutMouseExited
        // TODO add your handling code here:
        resetBg(btnSignOut);

    }//GEN-LAST:event_btnSignOutMouseExited

    private void btnAllCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllCourseActionPerformed
        // TODO add your handling code here:
        new AllCourses().setVisible(true);

    }//GEN-LAST:event_btnAllCourseActionPerformed

    private void btnAllCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllCourseMouseEntered
        // TODO add your handling code here:
        setBg(btnAllCourse);

    }//GEN-LAST:event_btnAllCourseMouseEntered

    private void btnAllCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllCourseMouseExited
        resetBg(btnAllCourse);
    }//GEN-LAST:event_btnAllCourseMouseExited

    private void btnUpdateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCourseActionPerformed
        // TODO add your handling code here:
        new UpdateCourse().setVisible(true);

    }//GEN-LAST:event_btnUpdateCourseActionPerformed

    private void btnNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCourseActionPerformed
        // TODO add your handling code here:
        //   setVisible(true);
        new NewCourse().setVisible(true);
    }//GEN-LAST:event_btnNewCourseActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:\
        setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCourseActionPerformed
        // TODO add your handling code here:
        new SeacrchCourse().setVisible(true);
    }//GEN-LAST:event_btnSearchCourseActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
        new DeleteCourse().setVisible(true);
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        new Students().setVisible(true);
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnNewCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewCourseMouseEntered
        // TODO add your handling code here:
        setBg(btnNewCourse);

    }//GEN-LAST:event_btnNewCourseMouseEntered

    private void btnSearchCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchCourseMouseEntered
        // TODO add your handling code here:
        setBg(btnNewCourse);


    }//GEN-LAST:event_btnSearchCourseMouseEntered

    private void btnUpdateCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateCourseMouseEntered
        // TODO add your handling code here:
        setBg(btnUpdateCourse);

    }//GEN-LAST:event_btnUpdateCourseMouseEntered

    private void btnDeleteCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteCourseMouseEntered
        // TODO add your handling code here:
        setBg(btnUpdateCourse);

    }//GEN-LAST:event_btnDeleteCourseMouseEntered

    private void btnStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseEntered
        // TODO add your handling code here:
        setBg(btnStudent);

    }//GEN-LAST:event_btnStudentMouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void btnNewCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewCourseMouseExited
        // TODO add your handling code here:
        resetBg(btnUpdateCourse);
    }//GEN-LAST:event_btnNewCourseMouseExited

    private void btnSearchCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchCourseMouseExited
        // TODO add your handling code here:
        resetBg(btnUpdateCourse);
    }//GEN-LAST:event_btnSearchCourseMouseExited

    private void btnUpdateCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateCourseMouseExited
        // TODO add your handling code here:
        resetBg(btnUpdateCourse);
    }//GEN-LAST:event_btnUpdateCourseMouseExited

    private void btnDeleteCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteCourseMouseExited
        // TODO add your handling code here:
        resetBg(btnDeleteCourse);
    }//GEN-LAST:event_btnDeleteCourseMouseExited

    private void btnStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseExited
        // TODO add your handling code here:
        resetBg(btnStudent);
    }//GEN-LAST:event_btnStudentMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private void setBg(JButton btn) {
        btn.setBackground(new java.awt.Color(0, 0, 255));
        btn.setForeground(new java.awt.Color(0, 0, 255));
    }

    private void resetBg(JButton btn) {
        btn.setBackground(new java.awt.Color(0, 0, 255));
        btn.setForeground(new java.awt.Color(0, 0, 255));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllCourse;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnNewCourse;
    private javax.swing.JButton btnSearchCourse;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnUpdateCourse;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
